### ISSUE TITLE
Uncaught TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by jongunter** [angular/in-memory-web-api#80] opened 2016-12-12 19:02 UTC
I followed the example for setting up the in-memory-web-api and I get the following error
```
reflection_capabilities.js:58 Uncaught TypeError: ctorParameters.map is not a function.
```
This occurred right after I added the following import line to my app.module.ts
```
InMemoryWebApiModule.forRoot(InMemoryDataService)
```

**Comment by jongunter** [comment] 2016-12-12 21:14
Apparently downgrading to 0.1.16 (I was at 0.1.17) fixed the issue for me.

**Comment by wardbell** [comment] 2016-12-13 00:02
There is no repro and no one else has reported this. Your solution is not something others should follow. Closing for lack of anything concrete to do.

**Closed by wardbell** 2016-12-13 00:02 UTC

**Comment by jongunter** [comment] 2016-12-13 15:36
The most recent release (last night) fixed it for me. Thank you.

My problem occurred on using CLI (webpack) on Windows 8. I started with a fresh project, added in the exact sample code shown on the home page of the repo.

**Comment by nikoTM** [comment] 2016-12-16 13:17
Happens to at least 2 other people using angular-cli@1.0.0-beta.19-3 on windows and osx. Works fine on Linux for me.

**Comment by mmathys** [comment] 2017-01-05 15:44
can confirm

**Comment by primaproxima** [comment] 2017-01-12 15:58
I also have this error using 1.1.17 of ng2-bootstrap.
angular 2.1.2

**Comment by azanebrain** [comment] 2017-01-21 04:49
I've found that this issue is caused by any number of packages expecting the version of Angular Core to be different than what is actually installed.

I was able to figure out the cause of this issue by looking at the error report from `ng build`:

    npm WARN @angular/platform-server@2.4.4 requires a peer of @angular/core@2.4.4 but none was installed.

This helped me realize that one of my packages expected Angular to be at v2.4.4, but I'm using v2.0.1. I updated my package.json to have both packages set to my core version like this:

    "dependencies": {
        "@angular/core": "2.0.1",
        "@angular/platform-server": "2.0.1",
    }

Your issue might not be with @angular/platform-server, but I hope this helps debug it
