### ISSUE TITLE
Is it necessary to have such a flat collections structure?

### ISSUE THREAD

**Issue by Hainesy** [angular/in-memory-web-api#153] opened 2017-11-08 15:49 UTC
Our API urls will probably be more nested than what in-memory-web-api seems to allow. Is there any way to customise the url per collection? Or do we have to create separate feature modules to get around this?

**Comment by nicwease** [comment] 2017-11-10 13:46
override the responseinterceptor() method and restructure the nested fields of the resOptions body property how you need. you can use a regex or something to match on a per URL basis

**Comment by nicwease** [comment] 2017-11-10 13:55
you might be able to do something like this by overriding the responseInterceptor() method. if you send a request to a particular URL that would not be returned by the service; then match that url and return the response you need from wherever.

**Comment by wardbell** [comment] 2017-12-10 11:03
I understand the need to return complex objects from real web  APIs.  The problem is that simulating all possible APIs and their structures is beyond the intention of this library which is to support the Angular documentation samples. The responseInterceptor may be the way to go.

Closing because we have no intention of pursuing this idea (worthy as it might be) .
If you come up with a way to do it and a PR, we'd certainly consider that.

**Closed by wardbell** 2017-12-10 11:03 UTC
